config/routes.rb
Rails.application.routes.draw do
  
  get 'static_pages/index'
  get 'static_pages/secret'
  root 'static_pages#index'

  resources :events
  post '/events', to:'events#create'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :attendances
  resources :charges
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
	belongs_to :user
	belongs_to :event
	
	after_create :welcome_send
	
	def welcome_send
		UserMailer.welcome_email(self).deliver_now
	end
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :admin, class_name:"User"
	has_many :attendances
	has_many :users, through: :attendances

	validates :start_date, presence:true
	validate :date_valable
	validates :duration, presence:true
	validate :multiple_5
	validates :title, presence:true #lenght:{in: 5..140}
	validates :description, presence:true #lenght:{in:20..1000}
	validates :price, presence:true  #lenght:{in:1..1000}
	validates :location, presence:true


	private

	def multiple_5
		if duration % 5 != 0
			return errors.add(:duration, 'Error,durate multiple of 5, retry again...')
		end
	end
	def date_valable
		if start_date < Time.now
			return errors.add(:start_date, 'Past event error, Retry to Futur event!')
		end
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	has_many :attendances
	has_many :events, through: :attendances
	has_many :admins, foreign_key:'admin_id', class_name: 'Event', dependent: :destroy

	after_create :welcome_send
	

	def welcome_send
		UserMailer.welcome_email(self).deliver_now
	end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
	before_action :authenticate_user!, only: [:new, :edit, :destroy]

	def new
		@events = Event.all
	end

	def edit
	end

	def create
	end

	def destroy
	end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	def index
	end

	def new
	end

	def create
	  # Amount in cents
	  @amount = 500

	  customer = Stripe::Customer.create({
	    email: params[:stripeEmail],
	    source: params[:stripeToken],
	  })

	  charge = Stripe::Charge.create({
	    customer: customer.id,
	    amount: @amount,
	    description: 'Rails Stripe customer',
	    currency: 'usd',
	  })

	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  redirect_to new_charge_path
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :authenticate_user!, only: [:new, :edit, :destroy]
    
	def index
	end 

	def show
		@events = Event.all
	end
	def update
		@event = Event.find(params[:id])
		@event.update(event_params)
		redirect_to event_path(@event.id)
	end
	def destroy
		@event = Event.find(params[:id])
		@event.destroy
		redirect_to event_path
	end
	def new
		@event = Event.new
	end
	def create
		@event = Event.create(event_params)
		redirect_to event_path(@event.id)
		
	end
	def edit
		@event = Event.find(params[:id])
	end
	
	
	
	
	private
	
	def event_params
		params.require(:event).permit(:start_date, :duration, :title, :description, :price, :location, :admin_id)
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	before_action :authenticate_user!, only:[:secret]
  def index
  end

  def secret
  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/attendances/new.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Gossip</title>
  <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	<style type="text/css">
		body{
			background-color: #20f020;
		}
		h1,h2,td{
			text-align: center;
			color: grey;
		}
	</style>
</head>
<body>
<table class="table">
  <thead>
    <tr>
      <td>START_DATE</td>
      <td>DURATION</td>
      <td>TITLE</td>
      <td>DESCRIPTION</td>
      <td>PRICE</td>
      <td>LOCATION</td>
      <td>ADMIN_ID</td>
      <td>Actions</td>
        <tbody>
    <% @events.each do |event|%>
    <tr>
      <td><%= event.start_date%></td>
      <td><%= event.duration %></td>
      <td><%= event.title %></td>
      <td><%= event.description %></td>
      <td><%= event.price %></td>
      <td><%= event.location %></td>
      <td><%= event.admin_id %></td>
      <td>
        
        <a href="<%= new_charge_path(event.id)%>" class="btn btn-primary">Join</a>
        
      </td>
    </tr>
      
    <% end %>
  </tbody>
  
    </tr>
  </thead>
</table>
</body>
</html>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>
<a href="<%= new_attendance_path %>" class="btn btn-primary">Retournez vous vers la page d'événement</a>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
    <p>You should empty the details :</p>
    <input type="text" name="first_name" placeholder="firstname"/>
    <input type="text" name="title" placeholder="title"/>

  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/events/edit.html.erb
<h1>Event#edit</h1>
<%= form_for @event do |f| %>
<div class="form-group">
	<%= f.text_field :start_date,placeholder: 'start_date',class: 'form-control' %>
	
</div>
<div class="form-group">
	<%= f.text_field :duration, placeholder: 'duration', class: 'form-control' %>
	
</div>
<div class="form-group">
	<%= f.text_field :title, placeholder: 'title', class: 'form-control' %>
	
</div>
<div class="form-group">
	<%= f.text_field :description, placeholder: 'description', class: 'form-control' %>
	
</div>
<div class="form-group">
	<%= f.text_field :price, placeholder: 'price', class: 'form-control' %>
	
</div>
<div class="form-group">
	<%= f.text_field :location, placeholder: 'location', class: 'form-control' %>
	
</div>
<div class="form-group">
	<button class="btn btn-primary" type="submit"> Edit event</button>
	
</div>
	
<% end %>

app/views/events/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Acceuil</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</head>
<body>

	<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="events/show">Accueil</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="events/new">new event<span class="sr-only">(current)</span></a>
      </li>
      
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Profil
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href=  <%= new_registration_path %> >S'inscrire</a>
          <a class="dropdown-item" href="devise/sessions/new">Se connecter</a>
          
      </li>
      
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>


</body>
</html>

app/views/events/new.html.erb
<h1>Event#new</h1>
<%= form_for @event do |f| %>
<div class="form-group">
	<%= f.text_field :start_date,placeholder: 'start_date',class: 'form-control' %>
	
</div>
<div class="form-group">
	<%= f.text_field :duration, placeholder: 'duration', class: 'form-control' %>
	
</div>
<div class="form-group">
	<%= f.text_field :title, placeholder: 'title', class: 'form-control' %>
	
</div>
<div class="form-group">
	<%= f.text_field :description, placeholder: 'description', class: 'form-control' %>
	
</div>
<div class="form-group">
	<%= f.text_field :price, placeholder: 'price', class: 'form-control' %>
	
</div>
<div class="form-group">
	<%= f.text_field :location, placeholder: 'location', class: 'form-control' %>
	
</div>
<div class="form-group">
	<%= f.text_field :admin_id, placeholder: 'admin_id', class: 'form-control' %>
	
</div>
<div class="form-group">
	<button class="btn btn-primary"  type="submit"> Create event</button>
	
</div>
	
<% end %>

app/views/events/show.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Gossip</title>
  <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	<style type="text/css">
		body{
			background-color: #20f020;
		}
		h1,h2,td{
			text-align: center;
			color: grey;
		}
	</style>
</head>
<body>
<table class="table">
  <thead>
    <tr>
      <td>START_DATE</td>
      <td>DURATION</td>
      <td>TITLE</td>
      <td>DESCRIPTION</td>
      <td>PRICE</td>
      <td>LOCATION</td>
      <td>ADMIN_ID</td>
      <td>Actions</td>
        <tbody>
    <% @events.each do |event|%>
    <tr>
      <td><%= event.start_date%></td>
      <td><%= event.duration %></td>
      <td><%= event.title %></td>
      <td><%= event.description %></td>
      <td><%= event.price %></td>
      <td><%= event.location %></td>
      <td><%= event.admin_id %></td>
      <td>
        <a href="<%= edit_event_path(event.id)%>" class="btn btn-primary">Editer</a>
        <a href="<%= event_path(event.id)%>" class="btn btn-danger" data-confirm="Vous voulez vraiment supprimer" data-method="delete">Supprimer</a>
      </td>
    </tr>
      
    <% end %>
  </tbody>
  
    </tr>
  </thead>
</table>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbrites</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Acceuil</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</head>
<body>

	<nav class="navbar navbar-expand-lg navbar-light bg-light">

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="events/show">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="events/new">Events</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="attendances/new">[Join events]</a>
      </li>

		<ul>
			<% if user_signed_in? %>
  <li>
      <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
    </li>

       

    <li>
      Voici ton email : <%= current_user.email %>
    </li>

    <li>
      <%= link_to "Profile", static_pages_secret_path %>
    </li>

    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>

  <% else %>
    <li>    
      <%= link_to "Sign in", new_user_session_path %>
    </li>

    <li>
      <%= link_to "Sign up", new_user_registration_path %>
    </li>

  <% end %>
</ul>


</nav>


  
    

</body>
</html>

app/views/static_pages/secret.html.erb
<head>
	<title>Gossip</title>
  <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	<style type="text/css">
		body{
			background-color: #20f020;
		}
		h1,h2,td{
			text-align: center;
			color: grey;
		}
	</style>
</head>
<h1>StaticPages#secret</h1>

<table class="table">
  <thead>
    <tr>
      <td>lastName</td>
      <td>email</td>
      <td>description</td>
        <tbody>

        	<% if user_signed_in? %>

    <tr>
      <td><%= current_user.last_name%></td>
      <td><%= current_user.email %></td>
      <td><%= current_user.description %></td>
      
    </tr>
      
    <% end %>
  </tbody>
  
    </tr>
  </thead>
</table>